# Yaml is white-space sensitive (use 2 spaces to indent).

# Define a new window with an id of 'bar'. This window can then be opened
# via the Zebar cli by running 'zebar open bar --args <ARGS...>'.
#
# Docs regarding window: https://some-future-docs-link.com
window/bar:
  providers: ["self"]
  # Width of the window in physical pixels.
  width: "{{ self.args.MONITOR_WIDTH }}"
  # Height of the window in physical pixels.
  height: "48"
  # padding: "5px 0px 0px 0px"
  # X-position of the window in physical pixels.
  position_x: "{{ self.args.MONITOR_X }}"
  # Y-position of the window in physical pixels.
  position_y: "{{ self.args.MONITOR_Y }}"
  # Whether to show the window above/below all others.
  # Allowed values: 'always_on_top', 'always_on_bottom', 'normal'.
  z_order: "normal"
  # Whether the window should be shown in the taskbar.
  shown_in_taskbar: false
  # Whether the window should have resize handles.
  resizable: false
  # Styles to apply globally within the window. For example, we can use
  # this to import the Nerdfonts icon font. Ref https://www.nerdfonts.com/cheat-sheet
  # for a cheatsheet of available Nerdfonts icons.
  global_styles: |
    @import "https://www.nerdfonts.com/assets/css/webfont.css";
  # CSS styles to apply to the root element within the window. Using CSS
  # nesting, we can also target nested elements (e.g. below we set the
  # color and margin-right of icons).
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: lightgreen;
    font-family: CaskaydiaCove Nerd Font SemiBold, monospace;
    font-size: 13px;
    padding: 5px 8px;
    background: #2b2b2b;
    border: 2px solid lightgreen;
    border-radius: 13px;
    # border-bottom: 1px solid rgb(255 255 255 / 5%);
    # background: linear-gradient(rgb(0 0 0 / 90%), rgb(5 2 20 / 85%));

    i {
      # color: rgb(115 130 175 / 95%);
      margin-right: 8px;
    }

  group/left:
    styles: |
      display: flex;
      align-items: center;

    # template/logo:
    #   styles: |
    #     margin-right: 20px;
    #   template: |
    #     <i class="nf nf-fa-windows"></i>

    template/glazewm_workspaces:
      styles: |
        display: flex;
        margin-right: 5px;
        justify-content: space-between;
        flex-grow: 1;
        align-items: center;

        .workspace {
          background: rgb(255 255 255 / 6%);
          # margin: 0px 4px;
          padding: 2px 5px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          color: white;
          border: none;
          border-radius: 30px;
          cursor: pointer;

          &.displayed {
            background: rgb(255 255 255 / 15%);
          }

          &.focused,
          &:hover {
            background: yellow; 
            color: black;
          }
        }
      providers: ["glazewm"]
      events:
        - type: "click"
          fn_path: "script.js#focusWorkspace"
          selector: ".workspace"
      template: |
        @for (workspace of glazewm.currentWorkspaces) {
          <button
            class="workspace {{ workspace.hasFocus ? 'focused' : '' }} {{ workspace.isDisplayed ? 'displayed' : '' }}"
            id="{{ workspace.name }}"
          >
            {{ workspace.displayName ?? workspace.name }}
          </button>
        }
    # template/title:
    #   styles: |
    #     # color: var(--Rosewater)
    #   providers: ["glazewm"]
    #   template: |
    #     @if ( glazewm.focusedContainer.type === 'window') {
    #       <span class="current-window"> {{ glazewm.focusedContainer.title }} </span>
    #     } @else {
    #       <span class="current-window"></span>
    #     }
  group/center:
    styles: |
      justify-self: center;
      color: white;
      font-size: 15px;

    template/clock:
      providers: ["date"]
      # Available date tokens: https://moment.github.io/luxon/#/formatting?id=table-of-tokens
      template: |
        {{ date.toFormat(date.now, 'EEE	dd MMM hh:mm:ss a') }}

  group/right:
    styles: |
      # justify-self: end;
      display: flex;
      flex-grow: 1;
      justify-content: space-between;
      align-items: center;

      .template {
          background: rgb(255 255 255 / 10%);
          # margin: 0px 4px;
          padding: 2px 6px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          border-radius: 30px;
          }

    template/glazewm_other:
      providers: ["glazewm"]
      styles: |
        display: flex;
        # margin-right: 6px;
        # width: 50px;

        .binding-mode, .tiling-direction {
          # background: rgb(255 255 255 / 15%);
          color: white;
          # border-radius: 2px;
          # padding: 2px 4px;
          # margin: 0;
        }

      template: |
        @for (bindingMode of glazewm.bindingModes) {
          <span class="binding-mode">
            {{ bindingMode.displayName ?? bindingMode.name }}
          </span>
        }

        @if (glazewm.tilingDirection === 'horizontal') {
          <span class="tiling-direction nf nf-md-swap_horizontal"></span>
        } @else {
          <span class="tiling-direction nf nf-md-swap_vertical"></span>
        }

    template/network:
      providers: ["network"]
      styles: |
        color: white;
        padding:0;

      template: |
        <!-- Show icon based on signal strength. -->
        @if (network.defaultInterface?.type === 'ethernet') {
          <i class="nf nf-md-ethernet_cable"></i>
        } @else if (network.defaultInterface?.type === 'wifi') {
          @if (network.defaultGateway?.signalStrength >= 80) {<i class="nf nf-md-wifi_strength_4"></i>}
          @else if (network.defaultGateway?.signalStrength >= 65) {<i class="nf nf-md-wifi_strength_3"></i>}
          @else if (network.defaultGateway?.signalStrength >= 40) {<i class="nf nf-md-wifi_strength_2"></i>}
          @else if (network.defaultGateway?.signalStrength >= 25) {<i class="nf nf-md-wifi_strength_1"></i>}
          @else {<i class="nf nf-md-wifi_strength_outline"></i>}
          Wifi
        } @else {
          <i class="nf nf-md-wifi_strength_off_outline"></i>
        }

    template/cpu:
      providers: ["cpu"]
      styles: |
        div {
          display: flex;
          align-items: center;
          color: #1E90FF;
        }

        .high-usage {
          color: #900029;
        }
      template: |
        <div><i class="nf nf-oct-cpu"></i>

        <!-- Change the text color if the CPU usage is high. -->
        @if (cpu.usage > 85) {
          <span class="high-usage">{{ Math.round(cpu.usage) }}%</span>
        } @else {
          <span>{{ Math.round(cpu.usage) }}%</span>
        } </div>

    template/memory:
      providers: ["memory"]

      styles: |
        div {
          display: flex;
          align-items: center;
          color: violet;
          
        }

      template: |
        <div><i class="nf nf-fae-chip"></i> {{ Math.round(memory.usage) }}%</div>

    template/battery:
      providers: ["battery"]
      styles: |
        position: relative;

        .charging-icon {
          position: absolute;
          font-size: 11px;
          left: 14px;
          top: 6px;
          color: #FF5733;
        }

        .orange {
          color: #ffa500;
        }

        .red {
          color: #ff4500;
        }

        .green {
          color: #33ff57;
        }

      template: |
        <!-- Show icon for whether battery is charging. -->
        @if (battery.isCharging) {<i class="nf nf-md-power_plug charging-icon"></i>}

        <!-- Show icon for how much of the battery is charged. -->
        @if (battery.chargePercent > 90 && battery.state === "discharging") {<i class="nf nf-fa-battery_4 orange"></i> <span class="orange">{{ Math.round(battery.chargePercent) }}%</span>}
        @else if (battery.chargePercent > 70 && battery.state === "discharging") {<i class="nf nf-fa-battery_3 orange"></i> <span class="orange">{{ Math.round(battery.chargePercent) }}%</span>}
        @else if (battery.chargePercent > 40 && battery.state === "discharging") {<i class="nf nf-fa-battery_2 orange"></i> <span class="orange">{{ Math.round(battery.chargePercent) }}%</span>}
        @else if (battery.chargePercent > 20 && battery.state === "discharging") {<i class="nf nf-fa-battery_1 orange"></i> <span class="orange">{{ Math.round(battery.chargePercent) }}%</span>}
        @else if (battery.chargePercent < 20 && battery.state === "discharging") {<i class="nf nf-fa-battery_0"></i>  <span class="red">{{ Math.round(battery.chargePercent) }}%</span>}
        @else {<i class="nf nf-fa-battery_4 green"></i> <span class="green">{{ Math.round(battery.chargePercent) }}%</span>}

    template/weather:
      providers: ["weather"]

      styles: |
        color: yellow;

      template: |
        @switch (weather.status) {
          @case ('clear_day') {<i class="nf nf-weather-day_sunny"></i>}
          @case ('clear_night') {<i class="nf nf-weather-night_clear"></i>}
          @case ('cloudy_day') {<i class="nf nf-weather-day_cloudy"></i>}
          @case ('cloudy_night') {<i class="nf nf-weather-night_alt_cloudy"></i>}
          @case ('light_rain_day') {<i class="nf nf-weather-day_sprinkle"></i>}
          @case ('light_rain_night') {<i class="nf nf-weather-night_alt_sprinkle"></i>}
          @case ('heavy_rain_day') {<i class="nf nf-weather-day_rain"></i>}
          @case ('heavy_rain_night') {<i class="nf nf-weather-night_alt_rain"></i>}
          @case ('snow_day') {<i class="nf nf-weather-day_snow"></i>}
          @case ('snow_night') {<i class="nf nf-weather-night_alt_snow"></i>}
          @case ('thunder_day') {<i class="nf nf-weather-day_lightning"></i>}
          @case ('thunder_night') {<i class="nf nf-weather-night_alt_lightning"></i>}
        }
        {{ weather.celsiusTemp }}°
